import * as THREE from 'three';
import {TrackballControls} from 'three/addons/controls/TrackballControls.js';
import {buildQ5Model} from './model.js';
import {createQ5View} from './three-view.js';
const element=<T extends HTMLElement>(id:string):T=>{const e=document.getElementById(id);if(!e)throw new Error(`Missing ${id}`);return e as T;};
function start():void{
 const model=buildQ5Model(),viewport=element<HTMLDivElement>('viewport'),renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.85;renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.domElement.setAttribute('aria-label','第五題可旋轉 3D 外觀模型');viewport.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color(0xeaf0ef);scene.add(new THREE.HemisphereLight(0xf6fbff,0x626553,.9));const key=new THREE.DirectionalLight(0xffffff,1.2);key.position.set(-180,620,300);scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,.35);fill.position.set(730,220,-400);scene.add(fill);
 const camera=new THREE.PerspectiveCamera(40,1,.1,6000),controls=new TrackballControls(camera,renderer.domElement);controls.rotateSpeed=2.1;controls.zoomSpeed=1.05;controls.panSpeed=.55;controls.staticMoving=true;controls.minDistance=45;controls.maxDistance=2200;
 const view=createQ5View(model);scene.add(view.root);const select=element<HTMLSelectElement>('component-select'),details=element<HTMLDivElement>('details');let selected='',terminalMarkers=false,isolated=false,disposed=false;
 const render=():void=>{if(!disposed)renderer.render(scene,camera);};controls.addEventListener('change',render);
 const setCamera=(position:THREE.Vector3,target:THREE.Vector3,up:THREE.Vector3):void=>{camera.up.copy(up);camera.position.copy(position);camera.lookAt(target);controls.target.copy(target);controls.update();render();};
 const setOverview=(kind='all'):void=>{
  isolated=false;view.isolate(null);terminalMarkers=false;view.showTerminals(null);element('show-terminals').classList.remove('active');for(const k of ['all','top','front'])element(`view-${k}`).classList.toggle('active',k===kind);
  const object=kind==='top'?view.root.getObjectByName('base'):kind==='front'?view.root.getObjectByName('operation'):view.root;view.root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(object??view.root),target=bounds.getCenter(new THREE.Vector3());const direction=(kind==='top'?new THREE.Vector3(0,1,.001):kind==='front'?new THREE.Vector3(1,0,0):new THREE.Vector3(-.84,1,.94)).normalize(),up=kind==='all'?new THREE.Vector3(0,1,0):new THREE.Vector3(0,0,-1),right=new THREE.Vector3().crossVectors(up,direction).normalize(),vertical=new THREE.Vector3().crossVectors(direction,right).normalize();const tanV=Math.tan(THREE.MathUtils.degToRad(camera.fov/2)),tanH=tanV*camera.aspect;let distance=100;
  for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const off=new THREE.Vector3(x,y,z).sub(target),depth=off.dot(direction);distance=Math.max(distance,depth+Math.abs(off.dot(right))/tanH,depth+Math.abs(off.dot(vertical))/tanV);}setCamera(target.clone().addScaledVector(direction,distance*1.09),target,up);updateDetails();
 };
 const focus=():void=>{const o=view.components.get(selected);if(!o)return;view.root.updateMatrixWorld(true);const s=new THREE.Box3().setFromObject(o).getBoundingSphere(new THREE.Sphere()),dist=Math.max(105,s.radius/Math.sin(THREE.MathUtils.degToRad(camera.fov/2))*1.24/Math.min(1,camera.aspect));setCamera(s.center.clone().add(new THREE.Vector3(.75,.8,1).normalize().multiplyScalar(dist)),s.center,new THREE.Vector3(0,1,0));};
 const append=(tag:string,text:string,cls='',parent:HTMLElement=details):HTMLElement=>{const e=document.createElement(tag);e.textContent=text;if(cls)e.className=cls;parent.appendChild(e);return e;};
 function updateDetails():void{
  details.replaceChildren();const c=model.components.find(c=>c.id===selected);
  if(!c){append('h2','第一版：盤面與元件外觀');append('div',`${model.components.length} 個可選物件 · 獨立模型預覽`,'subtle');append('p','已依照片還原底板、側立操作板、兩組接觸器與過載電驛、液面控制器、交替電驛及端子台。');append('div','接線資料尚未定案。此版不顯示既有線束，不提供通電測試；避免把照片裡看不清楚的接點猜成正確答案。','warning');append('h3','已保留的實物差異');append('p','照片追加的 FS 9P 轉接台與電極棒 3P 轉接台；操作板右側的 RL1 標籤。','subtle');append('p','點選模型或上方選單，再按「單獨查看」，可放大檢查元件。','subtle');return;}
  append('h2',`${c.id} · ${c.name}`);append('div',c.model,'subtle');append('span',`${c.terminals.length} 個模型端點`,'badge');append('span','尺寸非實測','badge');append('p',c.description);const related=model.issues.filter(i=>i.components.includes(c.id));if(related.length)append('div',related.map(i=>i.title).join('；')+'：尚未確認。','warning');
  const row=append('div','','row'),b=append('button',isolated?'返回盤面':'單獨查看','',row) as HTMLButtonElement;b.onclick=()=>{isolated=!isolated;view.isolate(isolated?selected:null);if(isolated)focus();else setOverview();updateDetails();render();};const f=append('button','聚焦元件','',row) as HTMLButtonElement;f.onclick=focus;
  append('h3','端子核對狀態');const list=append('div','');list.id='terminal-list';for(const t of c.terminals){const div=append('div',t.printedId??t.id,'terminal',list);div.title=t.note;append('span',t.positionVerified&&t.identityVerified?'照片可讀（座標近似）':t.positionVerified?'位置可見・端號待核':'實體位置待核','',div);}append('p','藍綠色＝可辨識標字與所在區域；橘色＝端號或位置仍待核對。所有端點尚未開放接線。','subtle');append('h3','照片來源');append('p',c.photos.join('、'),'subtle');
 }
 const choose=(id:string):void=>{selected=id;select.value=id;if(isolated){view.isolate(id||null);if(id)focus();else setOverview();}view.showTerminals(terminalMarkers&&id?id:null);updateDetails();render();};
 for(const c of model.components){const o=document.createElement('option');o.value=c.id;o.textContent=`${c.id} · ${c.name}`;select.appendChild(o);}select.onchange=()=>choose(select.value);for(const kind of ['all','top','front'])element(`view-${kind}`).onclick=()=>setOverview(kind);
 element('show-terminals').onclick=()=>{terminalMarkers=!terminalMarkers;element('show-terminals').classList.toggle('active',terminalMarkers);if(terminalMarkers&&!selected)choose('FS');else view.showTerminals(terminalMarkers?selected:null);render();};
 for(const i of model.issues){const div=append('div','','issue',element('issue-list'));append('strong',`${i.severity==='optional'?'可選':'待確認'} · ${i.title}`,'',div);append('span',i.request,'',div);}
 element('export-model').onclick=()=>{const blob=new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='q5-visual-model-v1.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);};
 let pointer:{x:number;y:number;id:number}|null=null;const ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>{pointer=e.isPrimary?{x:e.clientX,y:e.clientY,id:e.pointerId}:null;});renderer.domElement.addEventListener('pointercancel',()=>{pointer=null;});renderer.domElement.addEventListener('pointerup',e=>{if(!pointer||pointer.id!==e.pointerId)return;const moved=Math.hypot(e.clientX-pointer.x,e.clientY-pointer.y);pointer=null;if(moved>7)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObject(view.root,true).filter(h=>{let o:THREE.Object3D|null=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});const hit=hits.find(h=>h.object.userData.layer!=='label');const id:unknown=hit?.object.userData.componentId;if(typeof id==='string')choose(id);});
 const resize=():void=>{const w=viewport.clientWidth,h=viewport.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false);controls.handleResize();render();};const observer=new ResizeObserver(resize);observer.observe(viewport);resize();setOverview();element('loading').remove();const animate=():void=>{if(disposed)return;requestAnimationFrame(animate);controls.update();};animate();
 Object.defineProperty(window,'q5Review',{value:{model,scene,view,camera,renderer,choose,setOverview,focus,get selected(){return selected;},get isolated(){return isolated;}}});window.addEventListener('pagehide',()=>{disposed=true;observer.disconnect();controls.dispose();view.dispose();renderer.dispose();},{once:true});
}
try{start();}catch(error){document.getElementById('loading')?.remove();const box=document.createElement('div');box.className='error';box.textContent=`模型未能啟動：${error instanceof Error?error.message:String(error)}。請使用支援 WebGL 的 Safari／Chrome 開啟。`;document.getElementById('viewport')?.appendChild(box);console.error(error);}
