import * as THREE from 'three';
import type {ModelNode,Q5Model,Shape} from './model.js';
export interface Q5View{root:THREE.Group;components:Map<string,THREE.Group>;markers:THREE.Group;showTerminals(id:string|null):void;isolate(id:string|null):void;dispose():void}
/** Independent research view. No terminals are registered in the wiring engine. */
export function createQ5View(model:Q5Model,labels=true):Q5View{
 const root=new THREE.Group();root.name=model.version;root.userData={examId:model.examId,units:'nominal-mm',electricalSimulationEnabled:false};
 const components=new Map<string,THREE.Group>(),geometries=new Map<string,THREE.BufferGeometry>(),materials=new Map<string,THREE.Material>(),textures:THREE.Texture[]=[];
 const geometry=(s:Shape):THREE.BufferGeometry=>{const key=s.type==='label'?`label-${s.width}-${s.height}`:JSON.stringify(s);const old=geometries.get(key);if(old)return old;let g:THREE.BufferGeometry;
  switch(s.type){case'box':g=new THREE.BoxGeometry(...s.size);break;case'cylinder':g=new THREE.CylinderGeometry(s.topRadius??s.radius,s.radius,s.height,s.segments??24);break;case'torus':g=new THREE.TorusGeometry(s.radius,s.tube,8,32);break;case'sphere':g=new THREE.SphereGeometry(s.radius,24,12);g.scale(...s.scale);break;case'label':g=new THREE.PlaneGeometry(s.width,s.height);break;}geometries.set(key,g);return g;};
 const material=(n:ModelNode):THREE.Material=>{const s=n.shape;
  if(s?.type==='label'){const key=JSON.stringify(s),old=materials.get(key);if(old)return old;const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=Math.max(64,Math.round(1024*s.height/s.width));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('無法建立元件文字貼圖。');ctx.fillStyle=s.background;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle=s.foreground;ctx.textAlign='center';ctx.textBaseline='middle';const lines=s.text.split('\n');let size=Math.min(canvas.height/(lines.length+.45),100);do{ctx.font=`600 ${size}px Arial, "Noto Sans CJK TC", sans-serif`;if(lines.every(l=>ctx.measureText(l).width<canvas.width*.92))break;size-=2;}while(size>10);lines.forEach((l,i)=>ctx.fillText(l,canvas.width/2,canvas.height/2+(i-(lines.length-1)/2)*size*1.03));const t=new THREE.CanvasTexture(canvas);if('colorSpace'in t)t.colorSpace='srgb';t.anisotropy=2;textures.push(t);const m=new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});materials.set(key,m);return m;}
  const metal=n.layer==='hardware'||['#aab3b8','#d7dedf','#b57a43'].includes(n.color),key=`${n.color}-${n.opacity}-${metal}`,old=materials.get(key);if(old)return old;
  const m=new THREE.MeshStandardMaterial({color:n.color,metalness:metal?.48:.03,roughness:metal?.38:.68,transparent:n.opacity<1,opacity:n.opacity,depthWrite:n.opacity===1,side:n.opacity<1?THREE.DoubleSide:THREE.FrontSide});materials.set(key,m);return m;
 };
 const visit=(n:ModelNode,parent:THREE.Object3D):void=>{if(n.shape?.type==='label'&&!labels)return;const o=n.shape?new THREE.Mesh(geometry(n.shape),material(n)):new THREE.Group();o.name=n.id;o.position.set(...n.position);o.rotation.set(...n.rotation);o.userData={componentId:n.componentId,layer:n.layer};parent.add(o);if(!n.shape&&n.componentId&&o instanceof THREE.Group)components.set(n.componentId,o);
  if(n.layer==='cover'&&o instanceof THREE.Mesh){const g=new THREE.EdgesGeometry(o.geometry);geometries.set(n.id+'-edges',g);let m=materials.get('cover-edge');if(!m){m=new THREE.LineBasicMaterial({color:0x8da7ae,transparent:true,opacity:.45});materials.set('cover-edge',m);}o.add(new THREE.LineSegments(g,m));}n.children.forEach(child=>visit(child,o));};
 model.nodes.forEach(n=>visit(n,root));root.updateMatrixWorld(true);const markers=new THREE.Group();markers.name='review-terminal-markers';root.add(markers);
 const markerGeometry=new THREE.SphereGeometry(2.8,12,8);geometries.set('marker',markerGeometry);const known=new THREE.MeshBasicMaterial({color:0x0fabb6,depthTest:false}),unknown=new THREE.MeshBasicMaterial({color:0xf4ac38,depthTest:false});materials.set('known',known);materials.set('unknown',unknown);
 const showTerminals=(id:string|null):void=>{markers.clear();if(!id)return;const c=model.components.find(c=>c.id===id),o=components.get(id);if(!c||!o)return;root.updateMatrixWorld(true);for(const t of c.terminals){const m=new THREE.Mesh(markerGeometry,t.identityVerified&&t.positionVerified?known:unknown);m.position.set(...t.position);o.localToWorld(m.position);root.worldToLocal(m.position);m.renderOrder=99;m.userData={terminalId:t.id,componentId:id,wiringEnabled:false};markers.add(m);}};
 const isolate=(id:string|null):void=>{for(const group of root.children){if(group===markers)continue;for(const item of group.children)item.visible=id===null||item.userData.componentId===id;}};
 return{root,components,markers,showTerminals,isolate,dispose:()=>{for(const g of geometries.values())g.dispose();for(const m of materials.values())m.dispose();for(const t of textures)t.dispose();root.removeFromParent();}};
}
