import {WiringController} from './controller.js';
import {frontControls} from '../layout.ts';
export function createWirePanel(app,{toast,isFlapOpen,onChange}){
 const routing=new WiringController(app.world,app.components),front=new Set(frontControls.map(c=>c.id));
 let mode='connect',pending=null,busy=false;
 const panel=document.createElement('section');panel.className='wiring-panel';panel.innerHTML=`<div class="section-head"><h2>盤面配線</h2><span class="chip">黃色線</span></div><div class="toolgroup wire-modes"><button data-wire-mode="connect" class="active" aria-pressed="true">接線模式</button><button data-wire-mode="operate" aria-pressed="false">機構操作</button></div><p class="wire-prompt" role="status" aria-live="polite">點選起點端子，再點選終點端子。</p><div class="wire-actions"><button data-wire-cancel class="secondary" disabled>取消起點</button><button data-wire-undo class="secondary" disabled>復原上一條</button><button data-wire-all class="secondary" disabled>顯示全部</button></div><div class="wire-list" aria-label="已連接電線"></div><p class="wire-note">盤內沿線槽，操作板側直接走線。點線或清單可單獨追查；前方端子需展開操作板。這裡記錄配線，不計算電路通電。</p>`;
 document.querySelector('.select-wrap').before(panel);
 const $=s=>panel.querySelector(s),label=e=>`${e.component}:${e.terminal}`;
 function render(message){onChange?.();$('.wire-prompt').textContent=message||(busy?'正在檢查端子出口與走線…':pending?`起點 ${label(pending)} → 請點選終點`:(mode==='connect'?'點選起點端子，再點選終點端子。':'可操作按鈕與機構；切回接線模式即可加線。'));$('[data-wire-cancel]').disabled=!pending||busy;$('[data-wire-undo]').disabled=!routing.wires.length||busy;$('[data-wire-all]').disabled=!routing.selected;$('.wire-list').innerHTML=routing.wires.length?routing.wires.map(w=>`<div class="wire-row ${w.id===routing.selected?'active':''}"><button data-wire-id="${w.id}" aria-pressed="${w.id===routing.selected}"><b>${w.id}</b><span>${label(w.from)}<br>↳ ${label(w.to)}</span></button><button class="wire-delete" data-wire-delete="${w.id}" aria-label="刪除 ${w.id}">×</button></div>`).join(''):'<div class="wire-empty">尚未接線</div>';panel.querySelectorAll('[data-wire-id]').forEach(b=>b.onclick=()=>select(b.dataset.wireId));panel.querySelectorAll('[data-wire-delete]').forEach(b=>b.onclick=()=>{if(busy)return;routing.remove(b.dataset.wireDelete);render();});}
 function cancel(){pending=null;app.select(null);render();}
 function select(id){routing.select(routing.selected===id?null:id);render();}
 function frontAccessible(component){if(front.has(component)&&!isFlapOpen()){toast('請先用右上角「展開操作板」露出背面端子');return false;}return true;}
 async function pick(component,terminal){if(mode!=='connect'||busy||!frontAccessible(component))return;const endpoint={component,terminal};if(!pending){pending=endpoint;render();return;}if(label(pending)===label(endpoint)){toast('請點選另一個端子');return;}if(!frontAccessible(pending.component))return;busy=true;render();await new Promise(resolve=>setTimeout(resolve,30));try{const w=routing.connect(pending,endpoint);pending=null;render(`${w.id} 已接線 · ${label(w.from)} → ${label(w.to)}`);toast(`${w.id} 已接線`);}catch(e){render(e.message+'；起點已保留。');toast(e.message);}finally{busy=false;render($('.wire-prompt').textContent);}}
 function setMode(next){mode=next;pending=null;app.select(null);panel.querySelectorAll('[data-wire-mode]').forEach(q=>{const active=q.dataset.wireMode===mode;q.classList.toggle('active',active);q.setAttribute('aria-pressed',String(active));});document.querySelector('.hint').textContent=mode==='connect'?'點兩個端子接線 · 拖曳環繞 · 點線追查':'拖曳環繞 · 滾輪縮放 · 點選元件操作';render();}
 panel.querySelectorAll('[data-wire-mode]').forEach(b=>b.onclick=()=>{if(!busy)setMode(b.dataset.wireMode);});
 $('[data-wire-cancel]').onclick=cancel;$('[data-wire-undo]').onclick=()=>{const last=routing.wires.at(-1);if(last){routing.remove(last.id);render();}};$('[data-wire-all]').onclick=()=>{routing.select(null);render();};
 window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!busy)cancel();if((e.key==='Delete'||e.key==='Backspace')&&routing.selected&&!busy&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName)){e.preventDefault();routing.remove(routing.selected);render();}});
 render();document.querySelector('.hint').textContent='點兩個端子接線 · 拖曳環繞 · 點線追查';
 return {routing,pick,select,isConnect:()=>mode==='connect',isBusy:()=>busy,movePanel(open,previous){routing.movePanel(()=>app.setFlap(open,true),()=>app.setFlap(previous,true),front);setMode(open?'connect':'operate');},canMoveCover:id=>!busy&&!routing.hasComponent(id)};
}
