import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import * as T from 'three';
import {minimalProject,withAssembly} from './helpers/project-data.ts';
import {prepareLayoutCommand,snapCoordinate,quarterTurn,groupMembers} from '../src/editor/commands.ts';
import {LayoutController} from '../src/editor/controller.ts';
import {LayoutHistory} from '../src/editor/history.ts';
import {checkLayoutPlacement,definitionBounds} from '../src/editor/geometry.ts';
import {editorShortcut,crossedDragThreshold} from '../src/editor/input.ts';
import {HemisphereCamera} from '../src/camera.ts';
import type {ProjectDocument} from '../src/project/contracts.ts';
if(!globalThis.document)Object.defineProperty(globalThis,'document',{configurable:true,writable:true,value:{createElement:()=>({getContext:()=>({fillRect(){},strokeRect(){},fillText(){}})})}});
function empty(){const p=minimalProject();p.configuration.components=[];p.configuration.ducts=[];return p;}
const add={kind:'add' as const,definitionId:'shihlin-sp16',placement:{mountId:'base',position:[150,7,150] as [number,number,number],rotationY:0}};
test('builder entry point is wired into the application and scene',()=>{
 const app=fs.readFileSync(new URL('../src/project/app.ts',import.meta.url),'utf8');
 assert.match(app,/createLayoutEditor/);assert.match(app,/layoutUI\?\.active/);
 assert.ok(fs.existsSync(new URL('../src/editor/ui.ts',import.meta.url)));
 assert.match(fs.readFileSync(new URL('../src/scene.ts',import.meta.url),'utf8'),/setConstructionMode/);
});
test('finite grid and quarter-turn validation',()=>{assert.equal(snapCoordinate(116),120);assert.equal(snapCoordinate(-116),-120);assert.equal(quarterTurn(270),0);assert.equal(quarterTurn(-90),0);assert.throws(()=>snapCoordinate(NaN));assert.throws(()=>quarterTurn(4));});
test('add allocates independent IDs and does not mutate source',()=>{const p=empty(),before=structuredClone(p),a=prepareLayoutCommand(p,add),b=prepareLayoutCommand(a.project,add);assert.deepEqual(p,before);assert.notEqual(a.selectedId,b.selectedId);assert.equal(a.project.configuration.components.length,1);});
test('mount compatibility and unknown definitions reject before publication',()=>{assert.throws(()=>prepareLayoutCommand(empty(),{...add,definitionId:'missing'}));assert.throws(()=>prepareLayoutCommand(empty(),{...add,definitionId:'button-green'}));});
test('assembly rotates as one group and copying does not copy wires',()=>{const p=withAssembly();const r=prepareLayoutCommand(p,{kind:'rotate',id:'aux'});assert.equal(r.selectedId,'coil');assert.equal(r.changedIds.length,3);const c=prepareLayoutCommand(p,{kind:'copy',id:'coil',placement:{mountId:'base',position:[100,7,350],rotationY:90}});assert.equal(c.changedIds.length,3);assert.equal(groupMembers(c.project,c.selectedId!).length,3);assert.deepEqual(c.project.connections,p.connections);assert.equal(p.configuration.assemblies.length,1);});
test('attachment slots reject incompatible hosts and duplicate slots',()=>{const p=withAssembly();assert.throws(()=>prepareLayoutCommand(p,{kind:'attach',hostId:'coil',definitionId:'shihlin-ap22'}));assert.throws(()=>prepareLayoutCommand(p,{kind:'attach',hostId:'breaker',definitionId:'shihlin-ap22'}));});
test('deleting attached accessories preserves host; deleting host removes members',()=>{const p=withAssembly();const a=prepareLayoutCommand(p,{kind:'delete',id:'aux'});assert.ok(a.project.configuration.components.some(c=>c.id==='coil'));assert.equal(a.project.configuration.components.length,3);const b=prepareLayoutCommand(p,{kind:'delete',id:'coil'});assert.equal(b.project.configuration.components.length,1);assert.equal(b.project.configuration.assemblies.length,0);});
test('wired deletions require confirmation and fixed supply is protected',()=>{const p=minimalProject();p.connections=[{from:{component:'breaker',terminal:'2'},to:{component:'coil',terminal:'1L1'}}];assert.throws(()=>prepareLayoutCommand(p,{kind:'delete',id:'coil'}),/接線/);const r=prepareLayoutCommand(p,{kind:'delete',id:'coil',allowConnected:true});assert.equal(r.project.connections.length,0);const f=minimalProject();f.configuration.fixedConnections=[{from:{component:'breaker',terminal:'2'},to:{component:'coil',terminal:'1L1'}}];assert.throws(()=>prepareLayoutCommand(f,{kind:'delete',id:'coil',allowConnected:true}),/固定/);});
test('placement checks actual model bounds, collisions, ducts and board edges',()=>{const a=prepareLayoutCommand(empty(),add);assert.equal(checkLayoutPlacement(a.project,a.changedIds).valid,true);const b=prepareLayoutCommand(a.project,add);assert.equal(checkLayoutPlacement(b.project,b.changedIds).code,'component');const c=prepareLayoutCommand(empty(),{...add,placement:{...add.placement,position:[0,7,0]}});assert.equal(checkLayoutPlacement(c.project,c.changedIds).code,'bounds');a.project.configuration.ducts=[{id:'duct',mountId:'base',position:[150,.5,150],rotationY:0,width:40,length:200}];assert.equal(checkLayoutPlacement(a.project,a.changedIds).code,'duct');const box=definitionBounds('shihlin-sp16');assert.ok(box.max[0]>box.min[0]);});
test('controller failed publication leaves history and live project unchanged',async()=>{const initial=empty();const c=new LayoutController({read:()=>initial,canEdit:()=>true,load:async()=>{throw new Error('route failure');}});await assert.rejects(c.apply(add),/route failure/);assert.equal(c.busy,false);assert.equal(c.history.canUndo,false);assert.equal(initial.configuration.components.length,0);});
test('undo and redo advance only after successful load and can roll back failure',async()=>{let p=empty(),fail=false;const c=new LayoutController({read:()=>p,canEdit:()=>true,load:async next=>{if(fail)throw new Error('cancelled');p=next;}});await c.apply(add);fail=true;await assert.rejects(c.undo());assert.equal(p.configuration.components.length,1);assert.equal(c.history.canUndo,true);fail=false;await c.undo();assert.equal(p.configuration.components.length,0);await c.redo();assert.equal(p.configuration.components.length,1);});
test('controller rejects concurrent edits and editing during simulation',async()=>{let done:(()=>void)|undefined;const c=new LayoutController({read:empty,canEdit:()=>true,load:()=>new Promise<void>(resolve=>{done=resolve;})});const first=c.apply(add);await assert.rejects(c.apply(add));done!();await first;const locked=new LayoutController({read:empty,canEdit:()=>false,load:async()=>{}});await assert.rejects(locked.apply(add));});
test('history snapshots are isolated and bounded',()=>{const h=new LayoutHistory(2);const p=empty();h.record(p);p.name='changed';assert.notEqual(h.peekUndo()!.name,p.name);h.record(p);h.record(p);assert.equal(h.undoCount,2);h.clear();assert.equal(h.canUndo,false);});
test('builder keyboard respects text fields and native dialogs',()=>{const e={key:'r',ctrlKey:false,metaKey:false,shiftKey:false,altKey:false};assert.equal(editorShortcut(e,false,false),'rotate');assert.equal(editorShortcut(e,true,false),null);assert.equal(editorShortcut(e,false,true),null);assert.equal(editorShortcut({...e,key:'z',metaKey:true,shiftKey:true},false,false),'redo');assert.equal(crossedDragThreshold(3,3),false);assert.equal(crossedDragThreshold(7,0),true);});
test('orthographic construction projection and zoom preserve no perspective foreshortening',()=>{const camera=new T.OrthographicCamera(),o=new HemisphereCamera(camera);o.aspect=2;o.preset('construction');assert.equal(o.elevation,1.33);assert.equal(camera.right,-camera.left);assert.equal(camera.top,-camera.bottom);const width=camera.right-camera.left;o.zoom(-150);assert.ok(camera.right-camera.left<width);});
test('editor owns destructive wiring keys even while a dialog has focus',async()=>{const input=await import('../src/editor/input.ts');assert.equal(input.editorOwnsWiringKey('Delete'),true);assert.equal(input.editorOwnsWiringKey('Backspace'),true);assert.equal(input.editorOwnsWiringKey('Escape'),true);assert.equal(input.editorOwnsWiringKey('ArrowLeft'),false);});
test('editing a wired project really rebuilds the runtime and retains endpoint identities',async()=>{
 const {createProjectRuntime}=await import('../src/project/runtime.ts');const {ProjectSession}=await import('../src/project/session.ts');
 const session=new ProjectSession(createProjectRuntime(minimalProject()));session.active.connect({component:'breaker',terminal:'T1'},{component:'coil',terminal:'1L1'});
 const before=session.active.exportProject(),original=session.active;
 const c=new LayoutController({read:()=>session.active.exportProject(),canEdit:()=>!session.busy,load:async p=>{await session.load(JSON.stringify(p));}});
 try{await c.apply({kind:'move',id:'coil',placement:{mountId:'base',position:[356,7,106],rotationY:-90}});assert.notEqual(session.active,original);assert.deepEqual(session.active.exportProject().connections,before.connections);assert.equal(session.active.routing.wires.length,1);await c.undo();assert.deepEqual(session.active.exportProject(),before);}finally{session.dispose();}
});
